import { pageCopy } from './experience-copy.js';
// Recorded values originate in the pre-redesign workspace snapshot, 21 September 2026.
const recorded = (source) => ({ status: 'Recorded', source, verifiedAt: null });
export const actions = [
  { id: 'sisa-demo', type: 'Try demo', destination: 'https://sisa-demo.pika-xu.com', external: true, openMode: 'same', locales: { id: 'Coba Sisa', en: 'Try Sisa' }, verification: recorded('Legacy product record: demo URL') },
  { id: 'sisa-detail', type: 'View product', destination: '/sisa/', external: false, openMode: 'same', locales: { id: 'Tentang Sisa', en: 'About Sisa' }, verification: recorded('Compatibility contract C02') },
  { id: 'sisa-buy', type: 'Buy product', destination: 'https://pikaxustudio.gumroad.com/l/sisa-app', external: true, openMode: 'new', locales: { id: 'Beli Sisa di Gumroad', en: 'Buy Sisa on Gumroad' }, verification: recorded('Legacy product record: checkout URL') },
  { id: 'studio-contact', type: 'Contact email', destination: 'mailto:team@pika-xu.com', external: true, openMode: 'same', locales: { id: 'Email studio', en: 'Email the studio' }, verification: recorded('Legacy SiteFooter.astro; inbox operation unverified') },
];
export const studio = {
  name: 'Pika-Xu', contactActionId: 'studio-contact', productId: 'sisa', socialMediaId: 'studio-social', artworkMediaIds: [],
  locales: Object.fromEntries(['id', 'en'].map(locale => [locale, {status: 'Review', ...pageCopy[locale].home, headline: pageCopy[locale].home.title, intro: pageCopy[locale].home.description, body: pageCopy[locale].home.description}])),
};
export const demos = [{ id: 'sisa-lunch-example', mode: 'fixed-example', currency: 'IDR', initialAmount: 120000, expenseAmount: 35000 }];
export const offers = [{
  id: 'sisa-offer', productId: 'sisa', commercial: true, purchaseActionId: 'sisa-buy',
  price: { mode: 'On destination', amount: null, currency: null, source: 'Legacy price was null; pricing remains on Gumroad.' },
  purchaseDetails: { contents: null, access: null, demoLimits: null, verification: recorded('Migration contract C05: offer contents and fulfillment unverified') },
}];
export const media = [
  { id: 'studio-social', role: 'social-card', source: '/art/impression-studio.webp', width: 1200, height: 630, decorative: false, alt: 'Pika-Xu. Bikin hari-hari lebih mudah. Sisa, BagiBill, and Kertas Kecil Project.', rights: 'Original raster typography generated by scripts/create-impression-cards.py using local system fonts. No font files redistributed.', status: 'Review' },
  { id: 'sisa-social', role: 'social-card', source: '/art/impression-sisa.webp', width: 1200, height: 630, decorative: false, alt: 'Sisa. Kelola uang harian. Aplikasi pengelola uang.', rights: 'Original raster typography generated by scripts/create-impression-cards.py using local system fonts. No font files redistributed.', status: 'Review' },
];
export const productRecords = [{
  id: 'sisa', slug: 'sisa', name: 'Sisa', legacyName: 'sisa-app', kind: 'Stand-alone product',
  productTypes: ['Tool'], formats: ['Web app'], availability: 'Available', availabilityVerification: recorded('Legacy product record'),
  featured: true, offerId: 'sisa-offer', demoId: 'sisa-lunch-example', mediaIds: ['sisa-social'],
  actionPlacement: { hero: ['sisa-demo', 'sisa-detail'], purchase: ['sisa-buy'] },
  facts: [
    { id: 'offline', locales: { id: 'Mengutamakan penggunaan offline', en: 'Offline-first' }, verification: recorded('Legacy products.js: offline-first') },
    { id: 'account', locales: { id: 'Tanpa login atau akun', en: 'No login, no account' }, verification: recorded('Legacy products.js: no login, no account') },
    { id: 'storage', locales: { id: 'Data tersimpan di perangkat Anda', en: 'Data stays on your device' }, verification: recorded('Legacy products.js: data stays on your device') },
  ],
  locales: Object.fromEntries(['id', 'en'].map(locale => [locale, {status: 'Review', ...pageCopy[locale].sisa, oneLineBenefit: pageCopy[locale].sisa.description, summary: pageCopy[locale].sisa.description}])),
}];
export const content = { studio, products: productRecords, actions, offers, demos, media };
export const getProduct = (slug) => productRecords.find((product) => product.slug === slug);
export const getAction = (id) => actions.find((action) => action.id === id);
export const getOffer = (id) => offers.find((offer) => offer.id === id);
export const getDemo = (id) => demos.find((demo) => demo.id === id);
export const getMedia = (id) => media.find((item) => item.id === id);
